### ISSUE TITLE
Warning: componentWillReceiveProps has been renamed

### ISSUE THREAD

**Issue by micpob** [atlanteh/react-native-slot-machine#12]
Getting this warning message when using the Expo app on Android:

Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

**Comment by atlanteh** [comment]
Hey there @micpob! Thanks for posting this issue!
I no longer have an active react native env. Do you mind making a pr to get this fixed?

**Comment by jaythummar85** [comment]
Hey @micpob @atlanteh 

We can replace componentWillReceiveProps with componentDidUpdate. I have implement it and it is working fine.
The modification is given below. Let me know if you faced any issue with it.

```
componentWillReceiveProps(newProps) {
        if (newProps.text === this.text) {
            return;
        }
        this.text = newProps.text;
        const {range, duration, useNativeDriver} = newProps;
        const easing = Easing.inOut(Easing.ease);
        const paddedStr = this.getPaddedString(newProps);
        const newValues = this.getAdjustedAnimationValues(newProps);
        this.setState({values: newValues}, () => {
            const newAnimations = paddedStr.split('').map((char, i) => {
                const index = range.indexOf(char);
                const animationValue = -1 * (index) * newProps.height;
                return Animated.timing(this.state.values[i], {toValue: animationValue, duration, easing, useNativeDriver: useNativeDriver});
            });
            Animated.parallel(newAnimations).start();
        });
    }
```

with    
    
 ```
  componentDidUpdate(prevProps) {
    if (prevProps.text === this.props.text) {
      return;
    }
    this.text = this.props.text;
    const { range, duration, useNativeDriver } = this.props;
    const easing = Easing.inOut(Easing.ease);
    const paddedStr = this.getPaddedString(this.props);
    const newValues = this.getAdjustedAnimationValues(this.props);

    this.setState({ values: newValues }, () => {
      const newAnimations = paddedStr.split('').map((char, i) => {
        const index = range.indexOf(char);
        const animationValue = -1 * index * this.props.height;
        return Animated.timing(this.state.values[i], {
          toValue: animationValue,
          duration,
          easing,
          useNativeDriver: useNativeDriver,
        });
      });
      Animated.parallel(newAnimations).start();
    });
  }
```

**Comment by atlanteh** [comment]
~~Why do you have ```this.text = this.props.text;```? seems redundant. Am I right?~~

Nevermind. My bad. Created the PR.

**Comment by atlanteh** [comment]
I'm no longer working on React-Native, @jaythummar85 do you mind running few tests to make sure nothing is actually broken by this PR?  
You can do that by installing the PR:
```npm install atlanteh/react-native-slot-machine#pull/15/head```
and then run few manual tests to see everything works the same on initial load & on text updates

Thanks!

**Comment by jaythummar85** [comment]
Hello @atlanteh,

I have checked test cases with this PR:
`atlanteh/react-native-slot-machine#pull/15/head`
It is working fine in all cases. You can migrate it.

Thanks

**Comment by atlanteh** [comment]
#15 merged.
