### ISSUE TITLE
Can we use a word instead of single letter or single number? 

### ISSUE THREAD

**Issue by sfarazkhan** [atlanteh/react-native-slot-machine#13]
Hi,

Thanks for the great component. 
Can we use a word or string value as an option. like 'hi', 'hello', 'bye' and these three values spin?

**Comment by atlanteh** [comment]
Please have a look at the [advanced example](https://github.com/atlanteh/react-native-slot-machine#advanced-example)
Instead of emojis you can try putting words in there. You might need to adjust the styles.
