### ISSUE TITLE
Slot machine 9th column value goes only 2-8 range

### ISSUE THREAD

**Issue by avadhesh2828** [atlanteh/react-native-slot-machine#14]
When I give dynamically numbers one by one  then the  last column of my slot machine works only for 2-8 range .
I was take 0-9 range and total 9 column.
But it I see not working for 9 th column.
Others columns works absolutely fine.
Please help me for this issue.

**Comment by atlanteh** [comment]
Sorry for the long long delay. I'll be closing this issue now, as I imagine it's solved, but If this is still relevant, please provide a small example I can run and I'll check it. Thanks!
