### ISSUE TITLE
Display images instead of Text or numbers

### ISSUE THREAD

**Issue by tiofabby** [atlanteh/react-native-slot-machine#2]
Hello
Would there be a way to have images or icons being displayed instead of characters or numbers?
Thank you
Fabrice

**Comment by atlanteh** [comment]
Hi , sorry for the delay. I wrote this component as part of a project I'm working on. Currently I'm deep inside it so I don't have much time.
The development doesn't seem hard, but it requires testing to see there are no lags because images are much heavier than simple text.
A PR is welcome :)

**Comment by tiofabby** [comment]
Okay that would be wonderful!! I tried to create a PR but without much success. Thank you!!

**Comment by atlanteh** [comment]
I had some time this weekend and tried to add images support, but the images couldn't render fast enough and it didn't look good. Need to think about it more. If someone has an idea on how to do it, please share :)

**Comment by delef** [comment]
Still does not work correctly with the symbols of emoji, which is strange :(

🍏🍎🍐🍊🍋🍌

**Comment by atlanteh** [comment]
I checked it out, The reason is that these symbols are using two characters and not one.. I'll fix that in a few minutes.

**Comment by atlanteh** [comment]
@delef please check the latest update. I also added an example.

I'm going to close this issue as displaying icons and emojis is now supported. Currently I don't have any solution, using the current animation technic, for actual bundled images as they do not render quick enough.

**Comment by Manigandan-Azure** [comment]
@atlanteh any update on the image slots?

**Comment by atlanteh** [comment]
Sorry. Still no update
