### ISSUE TITLE
respin the slot machine

### ISSUE THREAD

**Issue by red62labs** [atlanteh/react-native-slot-machine#4]
not an issue really .
But is there any way to re spin the slot machine ? I have tried to call 
startIntitalAnimation(); but if it spins it is very slow.
please help thanks.

**Comment by atlanteh** [comment]
After the initial animation, if there's any text changes, the subsequent animations are just adjusting to the new text, not a new spin. What you want is a method to reset the animation?

**Comment by red62labs** [comment]
Sure to mimic a real slot machine .

**Comment by atlanteh** [comment]
Closed by 2a5b4629bf2dd2ae83cf604bfd0d9c441af58d9a
Please have a look at the new [spinTo](https://github.com/atlanteh/react-native-slot-machine#spintotext) method
