### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by jlorencelim** [atlanteh/react-native-slot-machine#5]
I tried having around 3-4 slot machine components and its very laggy. Is there a way that this can be fixed?

**Comment by atlanteh** [comment]
Android was always slower on animations than iOS.
Maybe there's a way if we change to native driver instead.
If you can test it, it would be great :)

**Comment by jlorencelim** [comment]
I tried it using the iOS through my device. Same result :(

**Comment by weswes** [comment]
Maybe we could have the "useNativeDriver" as a prop on SlotMachine ?
This way we'll be able to enable or disable it.

**Comment by atlanteh** [comment]
Sure we can, I'm a little busy over the next few days, so if someone can create a PR that will be great (just don't forget to update the docs).
It's a small pr but needs to be tested both in android and iOS.

**Comment by weswes** [comment]
I've made some tests and unfortunatly it's not so easy.
Native Animation only support non layout props. This module uses 'top' property to animate so we can't use Native Driver as is.
It could be possible by using translateY instead of top property.

**Comment by atlanteh** [comment]
Did you try to check with translateY?

**Comment by weswes** [comment]
It's done, I'll push a PR after testing on iOS.
Tests are ok on android and it's way better !

**Comment by atlanteh** [comment]
Awesome. Thx!

**Comment by atlanteh** [comment]
Published 0.3.2
